server:
  port: 8776
logging:
  level:
    #        tk.mybatis: DEBUG
    com.github.wxiaoqi.security.dzsw.sys: DEBUG
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${jar.ip}:8848
        #ip: 192.168.8.166
    sentinel:
      transport:
        dashboard: ${jar.ip}:8080
  application:
    name: ace-dzsw-sys
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# 必须配置
feign:
  authUrl: http://${jar.ip}:9777


# 配置swagger
swagger:
  enabled: true
  base-package: com.github.wxiaoqi.security.dzsw.sys
  title: ace-dzsw-sys
  version: 1.0.0.SNAPSHOT
  description: 电子商务服务系统
  contact:
    name: ccc

auth:
  client:
    id: ace-dzsw-sys
    secret: 123456

#redis-cache 相关
redis:
  # max-active: -1连接池最大连接数（使用负值表示没有限制）
  # max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  # max-idle: 8  # 连接池中的最大空闲连接
  # min-idle: 0  # 连接池中的最小空闲连接
  host: ${REDIS_HOST:${jar.ip}}
  port: ${REDIS_PORT:6379}
  password:
  # 服务或应用名
  sysName: ace-dzsw-sys

  #uploadconfig:
  # IMGSavePath: "F:/UploadFile/dzswSys/Img"
  # thumbnailSavePath: "F:/UploadFile/dzswSys/thumbnail/"
  #videoSavePath: "F:/UploadFile/dzswSys/Video/"

  #UploadFile:
  #ROOT_PATH: "F:"
  #SON_PATH: "/UploadFile/dzswImg/"
  # VIDEO_PATH: "/UploadFile/dzswVideos/"
  # THUMB_PATH: "/UploadFile/dzswThumbnail/"

jwt:
  issuer: zd
  subject: jianli
  token-header: Authorization
  expire: 14400000
  rsa-secret: xx1WET12^%3^(WE45

aliyun:
  accessKeyID: "LTAI4G1MHneg9uSD1EZNSdrt" #你的accessKeyID
  accessKeySecret: "DaihUnIocuY3FZ32VnGY3Z6pXyY8OR" #你的accessKeySecret
  domain: "dysmsapi.aliyuncs.com" #固定不变
  regionId: "cn-hangzhou" #固定不变
  templateCode: "SMS_203671139" #你的模板code
  signName: "中迪联创" #你的签名
  invalidtime: 5 #验证码失效时间 分钟
  phone-prefix: LOGIN,REGIST,FORGET_PASSWORD,UPDATE_MOBILE,UPDATE_PASSWORD,WX_UN_TYING,UPDATE_NEW_MOBILE
